name: Lint

on:
  pull_request:
    branches:
      - master
      - dev

permissions:
  contents: read

jobs:

  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.25.8

      - name: Run golangci-lint
        uses: step-security/golangci-lint-action@1797facf9ea427614d729a4e9cab0fae1a7852d9 # v9.2.0
        with:
          version: v2.10.1
          args: --timeout=5m
          only-new-issues: true
